package com.surf.surfhubds.brand

/**
 * Port do `BrandInfo.swift`. Metadados estáticos por brand (textos do carousel,
 * URLs de termos, WhatsApp, chatbot, força de update, MVNO etc).
 *
 * Uso: `BrandInfo.current(BrandResolver.current(context))`.
 */
data class BrandInfo(
    val carouselText1: String,
    val carouselText2: String,
    val carouselText3: String,
    val termsAdesaoURL: String = "",
    val termsOfertaURL: String,
    val termsPrivacidadeURL: String,
    val chatBotURL: String,
    val whatsApp: String,
    val forceUpdateURL: String,
    val coMvno: String,
    val mvnoName: String,
    val noMvno: String,
    val scheduleEligible: Boolean = true,
    val recurrenceEligible: Boolean = true,
) {
    companion object {
        fun current(brand: Brand): BrandInfo = when (brand) {
            Brand.FLACHIP -> BrandInfo(
                carouselText1 = "Bônus todo mês pra premiar quem é sócio-torcedor e assinante do FlaTV+",
                carouselText2 = "Aqui você pode programar suas recargas e ficar sempre conectado para postar aquela foto no Maraca.",
                carouselText3 = "Faça a portabilidade e ganhe bônus de internet todo mês!",
                termsOfertaURL = "https://fla-chip.com.br/regulamento-de-oferta/",
                termsPrivacidadeURL = "https://fla-chip.com.br/politica-de-privacidade/",
                chatBotURL = "https://bot-prd.bluelab.com.br/chat/public/chatbot?company=surftelecom&alias=flachipapp",
                whatsApp = "5521920001981",
                forceUpdateURL = "https://play.google.com/store/apps/details?id=br.com.surfmobile.flachip",
                coMvno = "324",
                mvnoName = "Fla-Chip",
                noMvno = "FLAMENGO",
                scheduleEligible = true,
                recurrenceEligible = true,
            )
            Brand.BANDSPORTS -> BrandInfo(
                carouselText1 = "A operadora de celular para você que é apaixonado por esportes.",
                carouselText2 = "Aqui você pode programar suas recargas\ne ficar sempre conectado.",
                carouselText3 = "Além de acompanhar seu consumo e\nescolher entre os melhores planos pré do \nmercado!",
                termsAdesaoURL = "https://bandsportscelular.com.br/termodeadesao/",
                termsOfertaURL = "https://bandsportscelular.com.br/regulamento-de-oferta-2/",
                termsPrivacidadeURL = "https://bandsportscelular.com.br/politicadeprivacidade/",
                chatBotURL = "https://bot-prd.bluelab.com.br/chat/public/chatbot?company=surftelecom&alias=surfbandsportsweb",
                whatsApp = "5521920001981",
                forceUpdateURL = "https://play.google.com/store/apps/details?id=br.com.surfmobile.bandsportscelular",
                coMvno = "1032",
                mvnoName = "BandSports Celular",
                noMvno = "BANDSPORTS CELULAR",
                scheduleEligible = true,
                recurrenceEligible = true,
            )
            Brand.CONECTA -> BrandInfo(
                carouselText1 = "A sua operadora de celular.",
                carouselText2 = "Aqui você pode programar suas recargas\ne ficar sempre conectado.",
                carouselText3 = "Além de acompanhar seu consumo e\nescolher entre os melhores planos pré do \nmercado!",
                termsAdesaoURL = "https://megasurfcelular.com.br/termo-de-adesao/",
                termsOfertaURL = "",
                termsPrivacidadeURL = "https://megasurfcelular.com.br/politica-de-privacidade/",
                chatBotURL = "https://bot-prd.bluelab.com.br/chat/public/chatbot?company=surftelecom&alias=megasurfapp&params=mtq5otc1ntq3ntu%3D",
                whatsApp = "5511933003030",
                forceUpdateURL = "https://play.google.com/store/apps/details?id=br.com.surfmobile.conectachip",
                coMvno = "98",
                mvnoName = "ConectaChip",
                noMvno = "BOTICARIO",
                scheduleEligible = true,
                recurrenceEligible = true,
            )
            Brand.MEGA -> BrandInfo(
                carouselText1 = "A sua operadora de celular.",
                carouselText2 = "Aqui você pode programar suas recargas e ficar sempre conectado.",
                carouselText3 = "Além de acompanhar seu consumo e escolher entre os melhores planos pré do mercado!",
                termsAdesaoURL = "https://megasurfcelular.com.br/termo-de-adesao/",
                termsOfertaURL = "",
                termsPrivacidadeURL = "https://megasurfcelular.com.br/politica-de-privacidade/",
                chatBotURL = "https://bot-prd.bluelab.com.br/chat/public/chatbot?company=surftelecom&alias=megasurfapp&params=mtq5otc1ntq3ntu%3D",
                whatsApp = "5511933003030",
                forceUpdateURL = "https://play.google.com/store/apps/details?id=br.com.surfmobile.megasurf",
                coMvno = "56",
                mvnoName = "Mega Surf Celular",
                noMvno = "MEGA MAIS",
                scheduleEligible = true,
                recurrenceEligible = true,
            )
            Brand.FLUXO -> BrandInfo(
                carouselText1 = "A sua operadora de celular.",
                carouselText2 = "Aqui você pode programar suas recargas\ne ficar sempre conectado.",
                carouselText3 = "Além de acompanhar seu consumo e\nescolher entre os melhores planos pré do \nmercado!",
                termsAdesaoURL = "",
                termsOfertaURL = "https://fluxoon.com.br/regulamento-de-oferta/",
                termsPrivacidadeURL = "https://fluxoon.com.br/politica-de-privacidade/",
                chatBotURL = "https://bot-prd.bluelab.com.br/chat/public/chatbot?company=surftelecom&alias=surffluxoonweb",
                whatsApp = "5511920140717",
                forceUpdateURL = "https://play.google.com/store/apps/details?id=br.com.surfmobile.fluxoon",
                coMvno = "1098",
                mvnoName = "Fluxo On",
                noMvno = "FLUXO ON",
                scheduleEligible = true,
                recurrenceEligible = true,
            )
            Brand.IFOOD -> BrandInfo(
                carouselText1 = "A operadora de celular que te acompanha em cada entrega.",
                carouselText2 = "Aqui entregador SUPER DIAMANTE tem plano GRÁTIS garantido todo mês.",
                carouselText3 = "Waze e Whatsapp ilimitado para te ajudar ainda mais na correria do dia a dia.",
                termsOfertaURL = "https://chipdoentregador.com.br/regulamento-de-ofertas/",
                termsPrivacidadeURL = "https://ifoodchip.com.br/politica-de-privacidade/",
                chatBotURL = "https://bot-prd.bluelab.com.br/chat/public/chatbot?company=surftelecom&alias=surfifoodweb",
                whatsApp = "5511920006010",
                forceUpdateURL = "https://play.google.com/store/apps/details?id=br.com.surfmobile.ifoodchip",
                coMvno = "1049",
                mvnoName = "iFood Chip",
                noMvno = "IFOOD",
                scheduleEligible = true,
                recurrenceEligible = true,
            )
            Brand.MATIZCONECTA -> BrandInfo(
                carouselText1 = "Aproveite os melhores planos com internet e ligações ilimitadas",
                carouselText2 = "Programe suas recargas e fique sempre conectado",
                carouselText3 = "Faça a portabilidade e ganhe bônus de internet",
                termsAdesaoURL = "",
                termsOfertaURL = "https://exemplo.com.br/regulamento-de-oferta",
                termsPrivacidadeURL = "https://exemplo.com.br/politica-de-privacidade",
                chatBotURL = "https://exemplo.com.br/chatbot",
                whatsApp = "5500000000000",
                forceUpdateURL = "https://apps.apple.com/br/app/exemplo/id0000000000",
                coMvno = "1126",
                mvnoName = "Bcs Prefeitura Maringa",
                noMvno = "BCS PREFEITURA DE MARINGA",
                scheduleEligible = true,
                recurrenceEligible = true,
            )
            Brand.PAFER -> BrandInfo(
                carouselText1 = "A sua operadora de celular.",
                carouselText2 = "Aqui você pode programar suas recargas\ne ficar sempre conectado.",
                carouselText3 = "Além de acompanhar seu consumo e\nescolher entre os melhores planos pré do \nmercado!",
                termsOfertaURL = "",
                termsPrivacidadeURL = "",
                chatBotURL = "https://bot-prd.bluelab.com.br/chat/public/chatbot?company=surftelecom&alias=paferweb",
                whatsApp = "5511922047991",
                forceUpdateURL = "https://play.google.com/store/apps/details?id=br.com.surfmobile.pafercelular",
                coMvno = "1155",
                mvnoName = "Pafer celular",
                noMvno = "PAFER",
                scheduleEligible = true,
                recurrenceEligible = true,
            )
            Brand.PAGUEMENOS -> BrandInfo(
                carouselText1 = "A sua operadora de celular.",
                carouselText2 = "Aqui você pode programar suas recargas\ne ficar sempre conectado.",
                carouselText3 = "Além de acompanhar seu consumo e\nescolher entre os melhores planos pré do \nmercado!",
                termsAdesaoURL = "https://paguemenoscelular.com.br/termo-de-adesao/",
                termsOfertaURL = "https://paguemenoscelular.com.br/regulamento-oferta/",
                termsPrivacidadeURL = "https://paguemenoscelular.com.br/politica-de-privacidade/",
                chatBotURL = "https://bot-prd.bluelab.com.br/chat/public/chatbot?company=surftelecom&alias=surfpaguemenosweb",
                whatsApp = "5585920002288",
                forceUpdateURL = "https://play.google.com/store/apps/details?id=br.com.surfmobile.paguemenoscelular",
                coMvno = "405",
                mvnoName = "PagueMenos Celular",
                noMvno = "PAGUE MENOS CELULAR",
                scheduleEligible = true,
                recurrenceEligible = true,
            )
            Brand.CARREFOURCHIP -> BrandInfo(
                carouselText1 = "A sua operadora de celular.",
                carouselText2 = "Aqui você pode programar suas recargas e ficar sempre conectado.",
                carouselText3 = "Além de acompanhar seu consumo e escolher entre os melhores planos pré do mercado!",
                termsAdesaoURL = "https://carrefourchip.surf.com.br/termo-de-adesao-2/",
                termsOfertaURL = "",
                termsPrivacidadeURL = "https://carrefourchip.surf.com.br/politica-de-privacidade/",
                chatBotURL = "https://bot-prd.bluelab.com.br/chat/public/chatbot?company=surftelecom&alias=carrefourwebchip",
                whatsApp = "5511933003030",
                forceUpdateURL = "https://play.google.com/store/apps/details?id=br.com.surfmobile.carrefourchip",
                coMvno = "69",
                mvnoName = "Carrefour Chip",
                noMvno = "CARREFOUR",
                scheduleEligible = true,
                recurrenceEligible = true,
            )
            Brand.CORREIOSCELULAR -> BrandInfo(
                carouselText1 = "A sua operadora de celular.",
                carouselText2 = "Aqui você pode programar suas recargas e ficar sempre conectado.",
                carouselText3 = "Além de acompanhar seu consumo e escolher entre os melhores planos pré do mercado!",
                termsAdesaoURL = "https://www.correioscelular.com.br/termos-de-adesao1/",
                termsOfertaURL = "",
                termsPrivacidadeURL = "https://www.correioscelular.com.br/politica-de-privacidade/",
                chatBotURL = "https://bot-prd.bluelab.com.br/chat/public/chatbot?company=surftelecom&alias=surftelecomappv2&params=null",
                whatsApp = "5511980002020",
                forceUpdateURL = "https://play.google.com/store/apps/details?id=br.com.surfmobile.correioscelular",
                coMvno = "1",
                mvnoName = "Correios celular",
                noMvno = "CORREIOS",
                scheduleEligible = true,
                recurrenceEligible = true,
            )
            Brand.UBER -> BrandInfo(
                carouselText1 = "A sua operadora de celular.",
                carouselText2 = "Aqui você pode programar suas recargas\ne ficar sempre conectado.",
                carouselText3 = "Além de acompanhar seu consumo e\nescolher entre os melhores planos pré do \nmercado!",
                termsAdesaoURL = "https://uberchip.com.br/termo-de-adesao/",
                termsOfertaURL = "https://uberchip.com.br/regulamento-oferta/",
                termsPrivacidadeURL = "https://uberchip.com.br/politica-de-privacidade/",
                chatBotURL = "https://bot-prd.bluelab.com.br/chat/public/chatbot?company=surftelecom&alias=surfuberweb",
                whatsApp = "5511920918719",
                forceUpdateURL = "https://play.google.com/store/apps/details?id=br.com.surfmobile.uberchip",
                coMvno = "48",
                mvnoName = "Uber Chip",
                noMvno = "UBER CHIP",
                scheduleEligible = true,
                recurrenceEligible = true,
            )
            Brand.PERNAMBUCANASCHIP -> BrandInfo(
                carouselText1 = "A sua operadora de celular.",
                carouselText2 = "Aqui você pode programar suas recargas e ficar sempre conectado.",
                carouselText3 = "Além de acompanhar seu consumo e escolher entre os melhores planos pré do mercado!",
                termsAdesaoURL = "https://pernambucanas.surf.com.br/termo-de-adesao-novo/",
                termsOfertaURL = "",
                termsPrivacidadeURL = "https://pernambucanas.surf.com.br/termo-de-privacidade-novo/",
                chatBotURL = "https://bot-prd.bluelab.com.br/chat/public/chatbot?company=surftelecom&alias=pernambucanaschipapp&params=mtq5otc1ntq3ntu%3D",
                whatsApp = "5511933003030",
                forceUpdateURL = "https://play.google.com/store/apps/details?id=br.com.surfmobile.pernambucanaschip",
                coMvno = "100",
                mvnoName = "Pernambucanas chip",
                noMvno = "PERNAMBUCANAS",
                scheduleEligible = true,
                recurrenceEligible = true,
            )
            Brand.DEFAULT -> BrandInfo(
                carouselText1 = "Aproveite os melhores planos com internet e ligações ilimitadas",
                carouselText2 = "Programe suas recargas e fique sempre conectado",
                carouselText3 = "Faça a portabilidade e ganhe bônus de internet",
                termsOfertaURL = "https://exemplo.com.br/regulamento-de-oferta",
                termsPrivacidadeURL = "https://exemplo.com.br/politica-de-privacidade",
                chatBotURL = "https://exemplo.com.br/chatbot",
                whatsApp = "5500000000000",
                forceUpdateURL = "https://play.google.com/store/apps/details?id=com.surf.default",
                coMvno = "000",
                mvnoName = "Surf",
                noMvno = "SURF",
                scheduleEligible = true,
                recurrenceEligible = true,
            )
        }
    }
}
